### ISSUE TITLE
[meta] re-design simple axes

### ISSUE THREAD

**Issue by hamilton** [graph-paper-org/graph-paper#78]
The axis components were authored as a bare-minimum non-reactive solution to "hey we need to see axis labels and ticks". As such, we should redesign them to account for everything we've learned about making everything else nicely reactive. 

Some directions:

- [x] redesign the simple axis to handle reactive changes (this is probably the heaviest lift)
- [x] change the nomenclature currently used to be a bit more understandable
- [x] add standard props for the long line
- [ ] add standard props for the ticks such as `tickSize`, `tickLength` etc.
- [ ] add props for the text labels such as `` `labelTextSize` `labelTextColor`, `labelTextWeight` etc. (these probably aren't the right name but it's not even 7am as I file this)
- [ ] add offset props to labels, or maybe align
- [ ] make the `time` axis components much more human-readable
